#cloud-config
coreos:
  units:
    - name: redirect-server.service
      command: start
      content: |
        [Unit]
        Description=Redirect Server
        After=docker.service

        [Service]
        TimeoutStartSec=0
        KillMode=none
        EnvironmentFile=/etc/environment
        ExecStartPre=-/usr/bin/docker kill redirect-server
        ExecStartPre=-/usr/bin/docker rm redirect-server
        ExecStartPre=/usr/bin/docker pull peleteiro/redirect-server
        ExecStart=/usr/bin/docker run --cap-add IPC_LOCK --hostname redirect-server --name redirect-server -p 0.0.0.0:80:8080 peleteiro/redirect-server
        ExecStop=/usr/bin/docker stop redirect-server
